const categoryData = [
  { nombre: "Líquidos", imagen: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=900&q=72" },
  { nombre: "Escobas y Trapeadores", imagen: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=900&q=72" },
  { nombre: "Aromatizantes", imagen: "https://images.unsplash.com/photo-1603712725038-e9334ae8f39f?auto=format&fit=crop&w=900&q=72" },
  { nombre: "Despachadores", imagen: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=900&q=72" },
  { nombre: "Bolsas", imagen: "https://images.unsplash.com/photo-1591193686104-fddba4d0e4d8?auto=format&fit=crop&w=900&q=72" },
  { nombre: "Cepillos y fibras", imagen: "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=900&q=72" },
  { nombre: "Cestos y cubetas", imagen: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=72" },
  { nombre: "Higiénicos", imagen: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?auto=format&fit=crop&w=900&q=72" }
];
const HOME_PRODUCT_LIMIT = 8;
let revealObserver;
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"})[c]);}
function normalizeText(value=""){return String(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();}
function normalizeHeader(value=""){return normalizeText(value).replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"");}
function parseCSV(text){const rows=[];let row=[],value="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quoted&&n==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(value);if(row.some(x=>String(x).trim()!==""))rows.push(row);row=[];value="";}else value+=c;}row.push(value);if(row.some(x=>String(x).trim()!==""))rows.push(row);return rows;}
function csvToObjects(text){const rows=parseCSV(text);if(rows.length<2)return[];const headers=rows[0].map(normalizeHeader);return rows.slice(1).map(row=>Object.fromEntries(headers.map((h,i)=>[h,String(row[i]??"").trim()])));}
function isTruthy(value,emptyDefault=false){const n=normalizeText(value);if(!n)return emptyDefault;return["true","verdadero","si","1","x","activo","visible","mostrar","destacado"].includes(n);}
function getPrice(product){const raw=product.precio??product.price??product.precio_venta;if(raw===null||raw===undefined||raw==="")return null;const v=Number(String(raw).replace(/,/g,"").replace(/[^0-9.-]/g,""));return Number.isFinite(v)?v:null;}
function formatPrice(value){return value===null?"Cotizar":new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(value);}
function normalizeImage(value=""){const image=String(value).trim();if(!image)return"";if(/^https?:\/\//i.test(image))return image;const clean=image.replace(/^\.?\//,"").replace(/^img\/productos\//i,"").replace(/^productos\//i,"");return`${MOBEL_CONFIG.imageBaseUrl}${encodeURI(clean)}`;}
function normalizeProduct(product,index){return{id:product.sku||product.id||`producto-${index+1}`,nombre:product.nombre||product.producto||"Producto",categoria:product.categoria||"Otros",descripcion:product.descripcion||"",imagen:normalizeImage(product.imagen||product.archivo_imagen_sugerido||product.foto||""),unidad:product.presentacion||product.unidad||"",precio:getPrice(product),destacado:isTruthy(product.destacado,false),mostrar:isTruthy(product.mostrar,true)};}
async function fetchProducts(){const sep=MOBEL_CONFIG.sheetCsvUrl.includes("?")?"&":"?";const response=await fetch(`${MOBEL_CONFIG.sheetCsvUrl}${sep}v=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`Error ${response.status}`);return csvToObjects(await response.text()).map(normalizeProduct).filter(p=>p.nombre&&p.mostrar);}
function observeReveal(element){if(!element)return;if(revealObserver)revealObserver.observe(element);else element.classList.add("in-view");}
function setupScrollAnimations(){const elements=document.querySelectorAll(".reveal");if(!("IntersectionObserver" in window)){elements.forEach(e=>e.classList.add("in-view"));return;}revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("in-view");revealObserver.unobserve(entry.target);}}),{threshold:.08,rootMargin:"0px 0px -30px 0px"});elements.forEach(observeReveal);}
function setupWhatsApp(){document.querySelectorAll("[data-whatsapp]").forEach(link=>{link.href=`https://wa.me/${MOBEL_CONFIG.whatsappNumber}?text=${encodeURIComponent(MOBEL_CONFIG.defaultMessage)}`;link.target="_blank";link.rel="noopener";});}
function categoryImage(name){const normalized=normalizeText(name);const match=categoryData.find(item=>normalized.includes(normalizeText(item.nombre).split(" ")[0]));return match?.imagen||categoryData[0].imagen;}
function renderCategories(products){const holder=document.getElementById("categoriesGrid");if(!holder)return;const categories=[...new Set(products.map(p=>p.categoria).filter(Boolean))].slice(0,8);holder.innerHTML=categories.map(category=>`<a class="category-card reveal" href="catalogo.html?categoria=${encodeURIComponent(category)}" aria-label="Ver productos de ${escapeHtml(category)}"><img src="${escapeHtml(categoryImage(category))}" alt="${escapeHtml(category)}" loading="lazy" decoding="async"><div class="category-card-content"><h3>${escapeHtml(category)}</h3><span>Ver productos <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></span></div></a>`).join("");holder.querySelectorAll(".reveal").forEach(observeReveal);}
function renderSkeletons(){const grid=document.getElementById("productsGrid");if(!grid)return;grid.innerHTML=Array.from({length:HOME_PRODUCT_LIMIT},()=>`<article class="product-card product-skeleton" aria-hidden="true"><div class="skeleton-image"></div><div class="product-content"><div class="skeleton-line skeleton-small"></div><div class="skeleton-line skeleton-title"></div><div class="skeleton-line"></div><div class="skeleton-line skeleton-button"></div></div></article>`).join("");}
function renderFeatured(products){const grid=document.getElementById("productsGrid"),empty=document.getElementById("emptyState");if(!grid)return;const featured=products.slice(0,HOME_PRODUCT_LIMIT);grid.innerHTML="";if(empty)empty.hidden=featured.length>0;featured.forEach((product,index)=>{const detailUrl=`producto.html?id=${encodeURIComponent(product.id)}`;const message=`Hola, me interesa el producto: ${product.nombre}. ¿Me pueden dar información?`;const whatsappUrl=`https://wa.me/${MOBEL_CONFIG.whatsappNumber}?text=${encodeURIComponent(message)}`;const description=product.descripcion||(product.unidad?`Presentación: ${product.unidad}`:"Solicita información y disponibilidad.");const card=document.createElement("article");card.className="product-card reveal";card.innerHTML=`<a class="product-image" href="${detailUrl}">${product.imagen?`<img src="${escapeHtml(product.imagen)}" alt="${escapeHtml(product.nombre)}" loading="${index<2?"eager":"lazy"}" decoding="async" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><div class="image-placeholder" style="display:none">🧴</div>`:`<div class="image-placeholder">🧴</div>`}</a><div class="product-content"><div class="product-meta"><span>${escapeHtml(product.categoria)}</span></div><h3><a href="${detailUrl}">${escapeHtml(product.nombre)}</a></h3><div class="product-price${product.precio===null?" product-price-quote":""}">${formatPrice(product.precio)}</div><p>${escapeHtml(description)}</p><div class="product-actions"><a class="btn btn-secondary" href="${detailUrl}">Ver producto</a><a class="icon-btn" href="${whatsappUrl}" target="_blank" rel="noopener" aria-label="Consultar por WhatsApp"><i class="fa-brands fa-whatsapp"></i></a></div></div>`;grid.appendChild(card);observeReveal(card);});}
async function loadHomeProducts(){renderSkeletons();try{const products=await fetchProducts();const featured=products.filter(p=>p.destacado);renderFeatured(featured.length?featured:products);renderCategories(products);const count=document.getElementById("productCount");if(count)count.textContent=`+${products.length}`;}catch(error){console.error(error);const grid=document.getElementById("productsGrid");if(grid)grid.innerHTML="";const empty=document.getElementById("emptyState");if(empty){empty.hidden=false;empty.textContent="No fue posible cargar los productos destacados.";}}}
function setupUseCategoriesCarousel(){const track=document.getElementById("useCategoriesTrack"),previous=document.querySelector(".use-carousel-prev"),next=document.querySelector(".use-carousel-next");if(!track||!previous||!next)return;const update=()=>{const max=track.scrollWidth-track.clientWidth;previous.disabled=track.scrollLeft<=4;next.disabled=track.scrollLeft>=max-4;};const move=direction=>track.scrollBy({left:direction*Math.max(track.clientWidth*.65,280),behavior:"smooth"});previous.addEventListener("click",()=>move(-1));next.addEventListener("click",()=>move(1));track.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);requestAnimationFrame(update);}
function setupMenu(){const toggle=document.getElementById("menuToggle"),nav=document.getElementById("mainNav");if(!toggle||!nav)return;toggle.addEventListener("click",()=>{nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(nav.classList.contains("open")));});nav.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>nav.classList.remove("open")));}
const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();setupScrollAnimations();setupMenu();setupWhatsApp();setupUseCategoriesCarousel();loadHomeProducts();
